/**
 * Every user-visible Hebrew UI string, in one place for the language editor.
 * Voice: plural address (men and women together): "כתבו", "שמרו", "מצאתם".
 * Answer content (data) is not here. Keys are grouped by screen; helpers build counted phrases.
 */

export const S = {
  common: {
    appName: 'אִיבַּעְיָא לְהוּ',
    bh: 'ב״ה',
    bhA11y: 'בעזרת השם',
    back: 'חזרה',
    topicA11y: (t: string) => `נושא: ${t}`,
    topicCountA11y: (t: string, n: number) => `${t}, ${n} שאלות`,
    readingTime: (min: number) => (min === 1 ? 'דקת קריאה' : `${min} דקות קריאה`),
  },
  tabs: {
    home: 'בית',
    topics: 'נושאים',
    saved: 'שמורים',
  },
  home: {
    morning: 'בוקר טוב',
    noon: 'צהריים טובים',
    evening: 'ערב טוב',
    night: 'לילה טוב',
    prompt: 'מה תרצו לשאול היום?',
    searchA11y: 'חיפוש שאלה',
    searchHint: 'פותח את מסך החיפוש',
    searchPlaceholder: 'כתבו או אמרו את השאלה',
    settings: 'הגדרות',
    daily: 'שאלת היום',
    readAnswer: 'לקריאת התשובה',
    topics: 'נושאים',
    allTopics: 'כל הנושאים',
    more: 'עוד',
    forYou: 'שאלות בשבילכם',
    all: 'הכול',
  },
  search: {
    title: 'חיפוש',
    placeholder: 'כתבו או אמרו את השאלה',
    inputA11y: 'שאלה לחיפוש',
    clear: 'ניקוי החיפוש',
    hint: 'אפשר לחפש במילים פשוטות, או לבחור נושא',
    closest: 'התשובות הקרובות ביותר',
    count: (n: number) => (n === 1 ? 'תשובה אחת' : `${n} תשובות`),
    notFoundTitle: 'לא מצאתם תשובה?',
    notFoundBody: 'אפשר לשלוח את השאלה כמו שהיא. נשתדל להוסיף עליה תשובה.',
    sentTitle: 'השאלה נשמרה',
    sentBody: 'תודה. נעדכן כשתהיה תשובה.',
    yourQuestion: 'השאלה שלכם',
    draftA11y: 'נוסח השאלה לשליחה',
    draftPlaceholder: 'נסחו את השאלה במילים שלכם',
    send: 'שליחת השאלה',
  },
  topics: {
    title: 'נושאים',
    total: (n: number) => `${n.toLocaleString('he-IL')} שאלות ותשובות`,
    count: (n: number) => (n === 1 ? 'שאלה אחת' : `${n} שאלות`),
    empty: 'אין עדיין שאלות בנושא הזה.',
  },
  saved: {
    title: 'שמורים',
    count: (n: number) => (n === 1 ? 'תשובה אחת שמורה' : `${n} תשובות שמורות`),
    emptyTitle: 'עוד לא שמרתם תשובות',
    emptyBody: 'בדף של כל תשובה אפשר לשמור אותה, והיא תחכה כאן.',
    toSearch: 'לחיפוש שאלה',
  },
  answer: {
    notFound: 'התשובה לא נמצאה.',
    appliesWhen: 'מתאים לכם אם',
    notWhen: 'פחות מתאים אם',
    toolbarSaved: 'נשמר',
    toolbarSave: 'שמירה',
    unsaveA11y: 'הסרה מהשמורים',
    saveA11y: 'שמירת התשובה',
    share: 'שליחה',
    shareA11y: 'שלחו בעדינות',
    smaller: 'הקטנה',
    smallerA11y: 'הקטנת הטקסט',
    larger: 'הגדלה',
    largerA11y: 'הגדלת הטקסט',
    read: 'הקראה',
    readA11y: 'הקראת התשובה',
    stop: 'עצירה',
    stopA11y: 'עצירת ההקראה',
    notAlone: {
      few: 'לא רק אתם: שאלה כזו עלתה כמה פעמים',
      tens: 'לא רק אתם: שאלה כזו עלתה עשרות פעמים',
      hundreds: 'לא רק אתם: שאלה כזו עלתה מאות פעמים',
    },
  },
  hardNow: {
    entry: 'קשה לי עכשיו',
    entryHint: 'פותח מסך שקט עם קווי סיוע',
    title: 'רגע קשה',
    helpTitle: 'אפשר לדבר עם מישהו עכשיו',
    helpNote: 'האפליקציה אינה תחליף לעזרה מקצועית. במצב חירום חייגו 101 או 100.',
    lines: {
      eran: { name: 'ער״ן', desc: 'עזרה ראשונה נפשית, כל שעות היממה' },
      sahar: { name: 'סה״ר', desc: 'צ׳אט אנונימי. א׳-ה׳ 16:00-03:00, שישי, שבת וערבי חג 18:00-00:00' },
      mda: { name: 'מד״א', desc: 'מצב חירום רפואי' },
      police: { name: 'משטרה', desc: 'סכנה מיידית' },
    },
    callA11y: (name: string, number: string) => `חיוג אל ${name}, ${number}`,
    chatA11y: (name: string) => `פתיחת הצ׳אט של ${name}`,
    chat: 'צ׳אט',
    readTitle: 'כמה מילים לרגע הזה',
    read: 'הקראה',
    stop: 'עצירה',
    readA11y: 'הקראת התשובה',
    stopA11y: 'עצירת ההקראה',
    full: 'לתשובה המלאה',
    draft: 'טיוטה',
  },
  share: {
    title: 'שלחו בעדינות',
  },
  settings: {
    title: 'הגדרות',
    theme: 'ערכת עיצוב',
    systemA11y: 'לפי הגדרת המכשיר (בהיר או כהה)',
    system: 'לפי המכשיר',
    systemDesc: (light: string, dark: string) => `${light} ביום, ${dark} בלילה`,
    themeA11y: (name: string) => `ערכת ${name}`,
    swatchTopic: 'זוגיות',
    swatchDaily: 'שאלת היום',
    swatchWordmark: 'אִיבַּעְיָא',
    textSize: 'גודל הטקסט',
    smallerA11y: 'הקטנת הטקסט',
    largerA11y: 'הגדלת הטקסט',
    textSample: 'כך ייראו התשובות: טקסט נוח לקריאה, בקצב שלכם.',
    readAloudSection: 'הקראה',
    readAloud: 'הקראת תשובות בקול',
    readAloudDesc: 'מוסיף כפתור הקראה בדף התשובה',
    editorSection: 'לעורכים',
    preview: 'תצוגת טיוטה',
    previewDesc: 'מציג גם פריטים שעוד לא אושרו',
  },
  themes: {
    '04': { name: 'נייר לבן ודיו', desc: 'לבן נקי ושחור דיו, כמו דף מודפס' },
    '07': { name: 'לילה וזהב', desc: 'שחור-אספרסו חם, טקסט שמנת ופליז' },
    '02': { name: 'חימר גולמי', desc: 'טיח אדובי בהיר, חום-קקאו ומסגרות ברונזה' },
    '05': { name: 'בית דפוס ישן', desc: 'דיו שחור על נייר שמנת עם אדום-רובריקה' },
    '06': { name: 'מרווה וזית', desc: 'ירוק מרווה, זית כהה וחול, מסגרות פליז' },
    '09': { name: 'ענן ומוקה', desc: 'לבן ענן, מוקה ושמפניה' },
    '10': { name: 'תכלת ופליז', desc: 'אפור-תכלת, אינדיגו עמוק ומסגרות פליז' },
  },
} as const;
